
type DockerContainer {
  id: String!
  name: String
  command: String
  createdAt: Date 
  runningFor: Date
  image: DockerImage
  labels: [DockerLabel!]!
  mounts: [DockerMount!]!
  size: String
  ports: [DockerPorts!]!
  status: DockerStatus!
}

type DockerContainerEvent {
  container: DockerContainer!
}
