

type DockerImage {
  id: String
  name: String!
  tag: String
  created: Date
  size: Number
  virtualSize: Number
  digest: String
  sharedSize: Number
  uniqueSize: Number
  containers: [DockerContainer!]!
}