config: BASE


args:
  main: false
  graphiql: false
  reload: false

paths:
  views: ${cwd}/renderer/views
  renderer:
    src: ${cwd}/renderer/dist
    dist: ${cwd}/renderer/dist
  icons: ${cwd}/icons

windows:

  base:
    width: 800
    height: 500
    center: true
    devtools: false
    autoHideMenuBar: true
    alwaysOnTop: false
    webPreferences:
      devTools: false
      nodeIntegration: true


  main:
    title: 'Main'
    backgroundColor: '#1d2125'
  
  graphiql:
    title: 'Graphiql'
    backgroundColor: '#ccc'

