config: BASE


args:
  main: false
  graphiql: false
  reload: false

paths:
  views: ${cwd}/renderer/views
  renderer:
    src: ${cwd}/renderer/dist
    dist: ${cwd}/renderer/dist
  icons: ${cwd}/icons

windows:
  
  main:
    width: 800
    height: 400
    alwaysOnTop: false
    devtools: false
    center: true
    title: 'Main'
    titleBarStyle: hidden
    backgroundColor: '#1d2125'
  
  graphiql:
    width: 800
    height: 500
    center: true
    alwaysOnTop: false
    devtools: false
    titleBarStyle: hidden
    backgroundColor: '#ccc'

