config: dev

windows:

  base:
    devtools: true
    webPreferences:
      devTools: true


  main:
    alwaysOnTop: true


# Проверка переменных
test:
  test: ${NODE_ENV}/index.js
  dirname: ${__dirname}
  filename: ${__filename}
  cwd: ${__cwd}